### ISSUE TITLE
Function failed to opne

### ISSUE THREAD

**Issue by Supecc** [EarthObservation/rvt-arcgis-pro#2]
Hello I run in to one issue, which is keeping me from using this toolbox. It is kinda stupid but but I solved it and it may be problem for some so I will share. When you download file there is word ... master in its name, but I think the script is not expecting it and giving error. I just deleted this word and function is working just fine. 
Edit: speling

**Comment by zm8597** [comment]
Hello. Thank you for the issue report! :) I haven't realized that the branch name is added as a suffix to the downloaded file name. I will add to installation instructions to rename the downloaded file.
