### ISSUE TITLE
matplotlib/PIL load error on ArcGIS Pro 3.0.3

### ISSUE THREAD

**Issue by GDoerffel65** [EarthObservation/rvt-arcgis-pro#5]
Hi Ziga(s),
just tested RVT with Pro 3.0.3. Seems to run into a python compatability issue when trying to initialize/load blend_func.py:
![image](https://user-images.githubusercontent.com/37537171/210543314-8bdb40f5-8f3f-4f01-bcb8-0d66ddd8f09c.png)
![image](https://user-images.githubusercontent.com/37537171/210543384-fb345e74-b76c-4f0f-98ec-49a16d33d8e3.png)
![image](https://user-images.githubusercontent.com/37537171/210543456-0e80c16a-409e-4f12-a70b-6e0774f5da58.png)

ArcGIS Pro has these python lib versions installed now:
matplotlib 3.4.3
pillow/PIL 9.2.0

Regards
Guenter

**Comment by zm8597** [comment]
Hey Guenter 😃,
thank you for the report I will take a look and fix the issue.

**Comment by zkokalj** [comment]
I've tested on several versions, including 3.1 and it works well. I assume this was also resolved by reinstalling Python.
