### ISSUE TITLE
ArcGIS Pro v 3.3.0 - breaks SLRM (and possibly some others?)

### ISSUE THREAD

**Issue by portbury3031** [EarthObservation/rvt-arcgis-pro#8]
Hi there,

I'm a frequent user of RVT and have recently started using the Arc raster functions version, which is so useful! It's brilliant to be able to apply your visualisations to large mosaic Lidar datasets :-). 

I've just updated Arc to version 3.3.0 and that sadly seems to have broken the SLRM visualisation. I've not tried all the other visualisations, but SVF and the multi direction hillshade seem to still work ok.

The release notes for v 3.3.0 say they've upgraded the version of Python used in Arc (https://pro.arcgis.com/en/pro-app/latest/get-started/release-notes.htm) I wonder if that might have caused the problem? 

Best wishes

Richard

**Comment by zkokalj** [comment]
Thank you for raising up the issue. We'll look into it.

**Comment by portbury3031** [comment]
That's appreciated, many thanks :-)

**Comment by zkokalj** [comment]
Hi! Please download and test the latest version.

**Comment by zkokalj** [comment]
MSTP still has to be fixed

**Comment by NejcCoz** [comment]
I have just applied the update for MSTP. All functions have been tested and are now working on ArcGIS Pro v3.3.0.

**Comment by portbury3031** [comment]
The latest version works perfectly for me, very many thanks for updating it :-)
